# Generated by Django 5.2.8 on 2025-11-19 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_parent_phone_studentpoint_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', help_text='Emoji or icon identifier', max_length=50)),
                ('criteria_type', models.CharField(choices=[('homework_completion', 'Homework Completion %'), ('total_points', 'Total Points'), ('participation_count', 'Participation Count'), ('attendance_count', 'Attendance Count'), ('top_rank', 'Top Rank in Group')], default='total_points', max_length=50)),
                ('criteria_value', models.PositiveIntegerField(help_text='Threshold value for earning this badge (e.g., 90 for 90% homework completion)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='interactiveitem',
            name='time_limit',
            field=models.PositiveSmallIntegerField(default=60, help_text='Time limit in seconds for answering this question'),
        ),
        migrations.CreateModel(
            name='MotivationalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('improvement', 'Improvement'), ('achievement', 'Achievement'), ('encouragement', 'Encouragement'), ('milestone', 'Milestone')], default='encouragement', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivational_messages', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('points_per_question', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='core.interactivecategory')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='core.group')),
                ('questions', models.ManyToManyField(blank=True, related_name='tournaments', to='core.interactiveitem')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_badges', to='core.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges_earned', to='core.student')),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('student', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to='core.student')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.tournament')),
            ],
            options={
                'ordering': ['-score', 'completed_at'],
                'unique_together': {('tournament', 'student')},
            },
        ),
    ]
